"""Ask — natural-language chat interface to the cancer-center data."""

from __future__ import annotations

import streamlit as st

from cu_openalex.cancer_center import chat
from cu_openalex.cancer_center.dashboard import shared

EXAMPLES = [
    "Which programs collaborate most with Cancer Prevention & Control?",
    "Top 10 most-cited publications since 2020 and their journals.",
    "How has inter-programmatic collaboration changed over the last decade?",
    "Which members publish the most in immunology?",
    "What share of our publications are open access by program?",
]


def main() -> None:
    shared.setup_page("Ask the Data", icon="💬", wide=False)
    st.markdown(
        "Ask questions in plain English. Answers are generated by querying the "
        "cancer-center tables live — every number is backed by a SQL query you "
        "can inspect."
    )

    if not chat._api_key():
        st.warning(
            "The chat service isn't configured (no `GEMINI_API_KEY` on the server). "
            "You can still explore the data on the other pages."
        )

    with st.sidebar:
        st.caption("Try an example:")
        for ex in EXAMPLES:
            if st.button(ex, use_container_width=True):
                st.session_state["pending"] = ex

    if "messages" not in st.session_state:
        st.session_state["messages"] = []

    for msg in st.session_state["messages"]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
            for sql in msg.get("queries", []):
                with st.expander("SQL"):
                    st.code(sql, language="sql")
            for tbl in msg.get("tables", []):
                st.dataframe(tbl, use_container_width=True, hide_index=True)

    prompt = st.chat_input("Ask about publications, programs, members, impact…")
    prompt = prompt or st.session_state.pop("pending", None)
    if not prompt:
        return

    st.session_state["messages"].append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Querying…"):
            result = chat.ask(prompt)
        if result.error:
            st.error(result.error)
            answer = result.answer or "_(no answer)_"
        else:
            answer = result.answer
        st.markdown(answer)
        for sql in result.queries:
            with st.expander("SQL"):
                st.code(sql, language="sql")
        for tbl in result.tables[-1:]:  # show the final result table
            st.dataframe(tbl.to_pandas(), use_container_width=True, hide_index=True)

    st.session_state["messages"].append(
        {
            "role": "assistant",
            "content": answer,
            "queries": result.queries,
            "tables": [t.to_pandas() for t in result.tables[-1:]],
        }
    )


main()
